name: Build and Deploy .NET App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Đăng nhập SSH và deploy
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd C:\Users\ADMIN\source\repos\RestX
            git pull origin master
            docker compose down
            docker compose up -d --build
          dotnet-version: '9.0.301' # Thay theo version em dùng

      # 3. Restore packages
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build project
      - name: Build
        run: dotnet build --no-restore

      # 5. Chạy test (nếu có)
      #- name: Test
      # run: dotnet test --no-build --verbosity normal

      # 6. Publish
      - name: Publish
        run: dotnet publish RestX.WebApp/RestX.WebApp.csproj -c Release -o ./publish
      #TEST CICDD
