name: Build and Deploy .NET App

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy source từ repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Cài đặt .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.301' # Thay theo version em dùng

      # 3. Restore packages
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build project
      - name: Build
        run: dotnet build --no-restore

      # 5. Chạy test (nếu có)
      #- name: Test
      # run: dotnet test --no-build --verbosity normal

      # 6. Publish
      - name: Publish
        run: dotnet publish RestX.WebApp/RestX.WebApp.csproj -c Release -o ./publish
      #TEST CICDD
